name: Spell checking
on:
  pull_request_target:
  push:
  issue_comment:

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: ${{ github.event_name == 'push' ||
        (
          contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      uses: actions/checkout@v2
    - uses: check-spelling/check-spelling@prerelease
      id: spelling
      if: ${{ github.event_name != 'issue_comment' ||
        (
          contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      with:
        suppress_push_for_open_pull_request: 1
        experimental_apply_changes_via_bot: 1
        extra_dictionaries:
          cspell:cpp/cpp.txt
          cspell:node/node.txt
          cspell:npm/npm.txt
          cspell:php/php.txt
          cspell:aws/aws.txt
          cspell:html/html.txt
          cspell:golang/go.txt
          cspell:django/django.txt
          cspell:css/css.txt
          cspell:filetypes/filetypes.txt
          cspell:en_GB/src/wordsEnGb.txt
          cspell:scala/scala.txt
          cspell:java/java.txt
          cspell:dotnet/dotnet.txt
          cspell:ruby/ruby.txt
          cspell:fullstack/fullstack.txt
          cspell:csharp/csharp.txt
